sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gamberri/docker-react -f Dockerfile.dev .

script:
  - docker run gamberri/docker-react npm run test -- --coverage
